#!/usr/bin/env php
<?php
$vendor_paths = [
    __DIR__,
    dirname(__DIR__),
    dirname(dirname(__DIR__)),
    dirname(dirname(dirname(__DIR__))),
];
$vendor_paths = array_filter($vendor_paths, function ($val) {
    $autoload_path =  $val.'/vendor/autoload.php';
    if (file_exists($autoload_path)) {
        require_once($autoload_path);
        return true;
    }
    return false;
});
if (empty($vendor_paths)) {
    die("Reader can not load vendor!\n");
}
if (php_sapi_name() != 'cli') {
    exit("Please run in cli! \n");
}

$current_path = getcwd();

$getOpt = new \GetOpt\GetOpt([
    \GetOpt\Option::create('v', 'vendor', \GetOpt\GetOpt::OPTIONAL_ARGUMENT)
        ->setDescription('vendor dir path')
        ->setDefaultValue($current_path.'/vendor'),
    \GetOpt\Option::create('o', 'output', \GetOpt\GetOpt::OPTIONAL_ARGUMENT)
        ->setDescription('output dir path')
        ->setDefaultValue($current_path),
    \GetOpt\Option::create('c', 'config', \GetOpt\GetOpt::OPTIONAL_ARGUMENT)
        ->setDescription('config json file')
        ->setDefaultValue($current_path.'/vendor-phar.json'),
    \GetOpt\Option::create('h','help', \GetOpt\GetOpt::NO_ARGUMENT)
        ->setDescription('Show this help and quit'),
]);

$getOpt->process();

if ($getOpt->getOption('help')) {
    exit(PHP_EOL. $getOpt->getHelpText());
}

$vendor = $getOpt->getOption('vendor');
$output = $getOpt->getOption('output');

$config_file = $getOpt->getOption('config');
$config = json_decode(file_get_contents($config_file), 1);
if ($config) {
    $vendor = !empty($config['vendorDir']) ? $config['vendorDir'] : $vendor;
    $output = !empty($config['baseDir']) ? $config['baseDir'] : $output;
    $excludes = !empty($config['exclude']) ? $config['exclude'] : [];
}

$packager = new \MMHK\VendorPhar\Packager($vendor, $excludes);
$packager->export($output);